/* ---------- Seeded RNG ---------- */
function mulberry32(seed) {
  return function () {
    let t = seed += 0x672B79F5;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashSeed(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(31, h) + str.charCodeAt(i) | 0;
  }
  return h >>> 0;
}

/* ---------- Tbles ---------- */
const tables = {
  person: ["my brother",
    "my sister",
    "my dad",
    "my mom",
    "my brother",
    "my sister",
    "my dad",
    "my mom",
    "my brother",
    "my sister",
    "my brother",
    "my sister",
    "my friend Evan",
    "my friend Harry",
    "my friend Austin",
    "my friend Alex",
    "my friend Kaden",
    "a random person",
    "the Director of Operations for the Ohio Soybean Council",
    "my union rep",
    "my former boyscout leader",
    "an engineer from another company (who has been a giant pain to work with)",
    "a coworker",
    "a retired coworker",
    "someone named Chariz",
    "someone who can fit seven apricots in his mouth",
    "the newest county judge",
    "the owner of my local game store",
    "a guy at the my local game store (who has done nothing but play esper control for the last ten years)",
    "someone I met at Dollar General",
    "the reincarnation of George Berkeley",
    "my accountant",
    "my ex",
    "my only coworker who watches anime",
    "the youngest police officer in my town",
    "a guy who kinda looks like Charlie Day",
    "the chairman of my local historical society",
    "Greg (you know who you are)",
    "the only guy i've ever met who smokes blue American Spirits",
    "my 7' tall friend",
    "someone I havn't seen in a while",
    "the only woman in my engineering office",
    "the best cornhole player in the office",
    "the barista",
    "my pastor",
    "my spiritual director",
    "the Editor-In-Chief of the local paper",
    "my neighbor",
    "my cousin",
    "my doctor",
    "an expert in a dying field",
    "someone I barely know",
    "the most Italian guy I know",
    "the youth coordinator at my parish",
    "a guy who makes a mean eggplant parm",
    "that jerk who won't tell me her macaron recipe",
    "the friend that has a boat",
    "the friend that doesn't have a car",
    "my boss",
    "my AI girlfriend",
    "a redditor",
    "a professional singer",
    "my old professor",
    "a guy at the gym",
    "the lead singer of Blue Traveler's wife",
    "the daughter of a Lutheran pastor",
    "my worst enemy",
    "God"],
  food: ["bagel with cream cheese",
    "eggs with chorizo and sourdough bread",
    "oatmeal (I love chia seeds)",
    "a cappuccino",
    "rice and beans",
    "sushi",
    "pizza with mushrooms",
    "the soup that makes you blind",
    "some campbell's soup",
    "Walmart sushi",
    "deep freeze beef",
    "concrete paste",
    "a tub of insects",
    "hotdogs",
    "baklava",
    "a granny-smith apple",
    "a red delicious apple (gross), cut into slices",
    "Haggen-Dazs",
    "steak",
    "steak (as reference to Earthbound)",
    "cannellini beans https://ihaspinecone.github.io/updates/cannellini-beans.html ",
    "Chipotle",
    "McDonalds",
    "Subway (against my better judgement)",
    "food from my local north African restaurant (It's so good)",
    "Indian food",
    "authentic Ohio Chinese food",
    "food based on friend's recommendation",
    "food from an anime-themed bar in Dayton Ohio",
    "crunchwrap",
    "dimethyl hexane",
    "vegetable soup",
    "mac & cheese with frozen peas in it",
    "chicken seasoned with paprika",
    "chocolate",
    "gnocchi",
    "spaghetti with red sauce",
    "bacon and eggs (with turkey bacon)",
    "bacon and eggs",
    "spinach and artichoke dip",
    "bruschetta",
    "really good vinegar",
    "olive oil that was confiscated on my flight home from Italy (I got more)",
    "something I saw on scrandle https://scrandle.com ",
    "something I first heard about because of wordle",
    "nothing (fasting today)",
    "something new",
    "blueberries",
    "cucumber (they are pretty good uncooked with just salt)",
    "cucumber",
    "something mom would not approve of",
    "oatmeal cream pies",
    "cherry pie",
    "rhubarb pie",
    "risotto",
    "chicken that was grilled over charcoal",
    "Top Ramen",
    "the worst burger I've ever had in my life",
    "burger",
    "Armenian food",
    "homemade bread",
    "Thai food",
    "the finest pizza the Midwest has to offer",
    "pizza",
    "fajitas",
    "berocca",
    "the secret to happiness",
    "carnitas",
    "a one pot weeknight meal",
    "mac and cheese with all my leftovers on it",
    "buffalo sauce",
    "donuts",
    "vegan tacos",
    "strawberries dipped in chocolate",
    "loaded nachos",
    "french onion soup",
    "bone-in wings",
    "the third salad this week",
    "boiled chicken",
    "edibible facial cream",
    "wings that are way too hot",
    "what they ate in the Donner Party",
    "apple pie",
    "fried rice",
    "a meatball sub",
    "stew",
    "biscuits",
    "fruit salad",
    "macaroni salad",
    "a half rack of ribs",
    "coffee",
    "some polish food that I can't pronounce",
    "picnic sandwiches",
    "deep dish pizza",
    "haggis",
    "yakisoba",
    "sourdough bread",
    "taco salad",
    "a big chunk of meat on a bone",
    "like a ton of rice",
    "food made with scorpion venom"],
  place: ["in a Meier parking lot",
    "in a barn",
    "in a cow pasture",
    "at my local game store",
    "in a grocery store",
    "at the car dealership",
    "in an Aldi's",
    "inside my car",
    "in a rusted train car",
    "at my friend's house",
    "in the coffee shop I write at",
    "at the local Mexican resturant",
    "in the woods",
    "at the park",
    "along the bike trail",
    "at my favorite bird watching spot",
    "in a place I'll never tell",
    "during Adoration",
    "at the seminary I previously attended",
    "at the virtual golf bar",
    "where a local church burned down",
    "at work",
    "in my mind",
    "in front of my youth group",
    "behind my house",
    "along a canal",
    "inside an abandoned factory",
    "next to a bicycle museum",
    "in my town's historic downtown",
    "at a Walmart",
    "in the Greater Columbus Convention Center",
    "at movie night",
    "in the church parking lot",
    "a nice path along a river",
    "at the butcher shop",
    "in Chipotle",
    "on the patio at a local resturant",
    "at Hobby Lobby",
    "at a charming store that mostly sells train sets and western model kits",
    "at a local woman's clothing store",
    "at Kohl's",
    "at a local funeral home",
    "at the county title office",
    "at Goodwill",
    "at a local book store",
    "at a antique store",
    "at a beloved local place that's going out of business",
    "at Culver's",
    "in a stirp-mall parking lot",
    "in the virtual world",
    "in a place beyond the margins"],
  topic: [ "a listing on Facebook Marketplace for a safe where the owner doesn't know the correct combination",
  "the roman empire",
  "Hobby Lobby",
  "scrapbooking",
  "the Bechdel Test",
  "a tricky problem in Revit",
  "getting better earbuds",
  "the Totsuka Blade",
  "if I was an anime character what color my aura would be",
  "living in a simulation",
  "Youtube Shorts",
  "how to fillet a fish",
  "Werner Herzog",
  "basketball",
  "baseball",
  "boots",
  "the AI summary of my Pax Transhumanity essay",
  "the fact that Mike Tyson fought Logan Paul",
  "the video game version of I Saw the Sign https://youtu.be/C8H-k1z9Z7A?si=cOpR6-n2-jqCmpy_&t=68 ",
  "The Monty Hall Problem",
  "a 1-phase 2-wire panelboard",
  "hyperdulia",
  "a guy on YouTube who is building a greenhouse out of discarded wooden pallets",
  "a guy on YouTube who makes unique icecream by infusing the cream with pieces of wood",
  "https://www.youtube.com/@Chorocojo ",
  "https://www.youtube.com/@ClassicsOfGame ",
  "the fact that the Les Miserables movie may be Hugh Jackman's worst performance of all time",
  "what's stopping me from writing a 5-figure check to Doctors Without Borders",
  "the fact that a decrease in community activity correlates to a decrease in charitable work",
  "a badass birthday party invitation",
  "Magic: The Gathering (1997)",
  "Artifact: The DOTA Card Game",
  "Fargo (1996)",
  "Yu-Gi-Oh: The Abridged Series and how it's very Monty Python",
  "borders",
  "tea strainers",
  "Joe Abercrombie",
  "The Sengoku Jidai",
  "metric vs imperial units",
  "The Gospel of Thomas",
  "the best books of all time",
  "Arianism",
  "blue sticky notes",
  "the best flavor of tea",
  "The Onion",
  "A Fistfull of Dollars (1964)",
  "an egregious amount of information",
  "actuarial tables",
  "this image https://ihaspinecone.github.io/updates/thinking.webp ",
  "GFCI outlets",
  "my screename when I was 12",
  "the weather",
  "my health",
  "The Dark Knight Rises (2008)",
  "The Passion of the Christ (2004)",
  "how my 4th grade computer class made a We Didn't Start the Fire parody for some reason that i'm pretty sure we never finished",
  "wrist pain",
  "Dennis Prager",
  "Jordan Peterson",
  "HBomberGuy",
  "basic arithmatic",
  "something the british do wrong",
  "accumulating wealth",
  "Hellfire from The Hunchback of Notre Dame (1996)",
  "Black Midi",
  "Worm https://parahumans.wordpress.com ",
  "cows",
  "strawberries",
  "emails",
  "death",
  "Old Spice body wash",
  "Las Vegas",
  "breaking a hog trough at a wedding",
  "life",
  "changing the world",
  "world domination",
  "NEMA-3R dust-tight panels",
  "how lame computer science is",
  "the end of the world",
  "Hitchhiker's Guide to the Galaxy",
  "Speaker for the Dead",
  "how good Ohio's State Flag is",
  "To Live and Die in LA (1985)",
  "The Producers (1967)",
  "what'd I'd do differently if I were in charge",
  "how much rain was in the rain gauge",
  "Jackie Robinson's football career",
  "the health of all good men",
  "vaping",
  "9/11",
  "The Ohio State University",
  "Little Kuriboh's Spoof Series Show https://youtu.be/N17SGtrhQtQ?si=86LxXxKKwIA0_A80 ",
  "the office water filter (it needs replaced)",
  "cycling",
  "barefoot shoes",
  "packing a tobacco pipe",
  "plans for summer",
  "Weezer",
  "Riverdale",
  "Dungeons and Dragons",
  "Chess Boxing",
  "Cars",
  "Clint Eastwood",
  "comics",
  "mounting a tv on the ceiling",
  "the pharyngeal wall",
  "floor time",
  "the moral decline of society",
  "the act of talking about the Roman Empire",
  "The Silmarillion",
  "a book I read recently",
  "what I should've done differently",
  "AutoCAD",
  "my actual phone number",
  "basis of design and reference for the latest expansion of Clarios acid rollout facilities",
  "how to correctly copy and paste something",
  "bone conduction headphones",
  "blackout curtains",
  "what it's like to work the night shift",
  "Psychiatrist https://en.wikipedia.org/wiki/Psychiatrist_(game) ",
  "whether american spirits really do just use tobacco and water",
  "the beginning of life",
  "what I should be doing differently",
  "Ralph Bakshi's Lord of the Rings",
  "the documentary Garlic is as Good as 10 Mothers",
  "brownie recipes",
  "my time in Italy",
  "hiking the Camino",
  "Golden Kamuy",
  "analog synths",
  "the perfect vacation",
  "the biggest mistake I've ever made",
  "the top Substack writers",
  "the conflicts in Northern Ireland",
  "my favorite Magic The Gathering Set",
  "human cloning",
  "Those Who Walk Away from Omelas",
  "whether AI is 'creative'",
  "867-5309",
  "the smelliest mosh pit I've ever been in",
  "forums vs discord servers",
  "why cars are ugly now",
  "why cars can't have good microphones",
  "what it's like to accidently open the wrong 3D model in Revit",
  "my cheap chinese plastic vertical mouse that feels better than every expensive one I've ever used",
  "how dangerous wingsuits are",
  "a potential new hobby",
  "writing",
  "altnernate keyboard layouts to QWERTY",
  "car names",
  "the weirdo who gave my college commencement speech",
  "yelling",
  "how the 31st day of a month is actually a bonus day you can do whatever you want with",
  "Zero Punctuation",
  "America's role as the 'Arsenal of Democracy'",
  "Irish folk music",
  "Ed Sheeran",
  "my second wife",
  "the way electric guitar sounds"]
};

/* ---------- Helper ---------- */
function pick(arr, rng) {
  if (!arr || !arr.length) {
    console.error("pick() received invalid input:", arr);
    return null;
  }
  return arr[Math.floor(rng() * arr.length)];
}

/* ---------- Cases ---------- */
const cases = [
  { text: "Watched a YouTube video about (topic)." },
  { text: "Ate (food)." },
  { text: "Looked up recipes for (food)." },
  { text: "Looked up recipes for the <i>authentic</i> version of (food)." },
  { text: "Ordered (food)." },
  { text: "Talked to (person) about (food)." },
  { text: "Ate (food) while thinking about (topic)." },
  { text: "Ran into (person) (place)." },
  { text: "Learned about (topic) from (person)." },
  { text: "Tried making (food) for (person)." },
  { text: "Went (place) to study (topic)." },
  { text: "Discussed (topic) while enjoying (food)." },
  { text: "Saw (person) order (food)." },
  { text: "Argued with (person) about (topic)." },
  { text: "Shared (food) with (person)." },
  { text: "Listened to (person) talk about (topic)." },
  { text: "Dropped off (food) for someone (place)." },
  { text: "Ate some (food) (place)." },
  { text: "Gifted (food) to (person)." },
  { text: "Texted (person) about (topic)." },
  { text: "Studied (topic) while eating (food)." },
  { text: "Ran into (person) (place)." },
  { text: "Recorded a vlog about (topic) with (person)." },
  { text: "Walked around (place)." },
  { text: "Doordashed (food)." },
  { text: "I was there when (person) learned about (topic)." },
  { text: "Thought about the similarities between (topic) and (topic)." },
  { text: "Well, (person) convinced me about (topic)." },
  { text: "Played chess with (person)." },
];

const compiledCases = cases.map(c => {
  const parts = c.text.split(/(\(.*?\))/g);

  return parts.map(part => {
    const match = part.match(/^\((.*?)\)$/);
    if (match) return { type: "table", name: match[1] };
    return { type: "text", value: part };
  });
});

function createGenerator(seedInput) {
  const seed = hashSeed(seedInput);
  const rng = mulberry32(seed);

  return function generateOne() {
    const selected = compiledCases[Math.floor(rng() * compiledCases.length)];

    return selected.map(part => {
      if (part.type === "text") return part.value;
      return pick(tables[part.name], rng);
    }).join("");
  };
}

/*function runGenerator() {
  const seed = document.getElementById("seed").value;
  const generator = createGenerator(seed);

  let results = [];
  for (let i = 0; i < 40; i++) {
    results.push(`${i + 1}. ${generator()}`);
  }

  document.getElementById("result").innerHTML = results.join("<br>");
}*/
